refactor workflow structure for clarity and consistency

diff --git a/.github/workflows/01-buliding.yaml b/.github/workflows/01-buliding.yaml
--- a/.github/workflows/01-buliding.yaml
+++ b/.github/workflows/01-buliding.yaml
@@ -3,10 +3,19 @@ on: push
 
 
 jobs:
-    echo-hello:
-        runs-on: ubuntu-latest
-        steps:
-            - name: Echo Hello World
-              run: echo "Hello World"
-        
+  echo-hello:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Echo Hello World
+        run: echo "Hello World" 
+  echo-goodbye:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed Step
+        run: |
+          echo "This step will fail"
+          exit 1          
+      - name: Say Goodbye
+        run: echo "Goodbye World" 
+
               
